version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - COMMIT_ID=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=$COMMIT_ID
      - IMAGE_URI=047471737790.dkr.ecr.ap-south-1.amazonaws.com/cloudreport-api:$IMAGE_TAG
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $IMAGE_TAG .
      - docker tag $IMAGE_TAG 047471737790.dkr.ecr.ap-south-1.amazonaws.com/cloudreport-api:$IMAGE_TAG
  post_build:
    commands:
      - echo Pushing Docker images...
      - docker push $IMAGE_URI
      # - docker push 047471737790.dkr.ecr.ap-south-1.amazonaws.com/cloudreport-api:latest
      - echo Writing image definitions file...
      - |
        echo '[
          {
            "name": "fast-api",
            "imageUri": "'"$IMAGE_URI"'"
          }
        ]' > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json